apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fg8h5i2xk-nodejs 
  janus-idp.io/tekton: fg8h5i2xk-nodejs
  backstage.io/kubernetes-id: fg8h5i2xk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fg8h5i2xk-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  