apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fg8h5i2xk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fg8h5i2xk-nodejs 
  name: fg8h5i2xk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fg8h5i2xk-nodejs 
